# Generated by Django 4.1.7 on 2023-03-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('year_published', models.CharField(max_length=10)),
                ('review', models.FloatField()),
                ('author', models.ForeignKey(blank=True, db_column='author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='authors.author', verbose_name='author')),
            ],
            options={
                'db_table': 'dim_all_books',
            },
        ),
    ]
