# Generated by Django 4.1.7 on 2023-03-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_author_name_author_author_name'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.ForeignKey(blank=True, db_column='author_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='authors.author', verbose_name='author_name'),
        ),
    ]
