# Generated by Django 4.1.7 on 2023-03-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_author_name_author_author_name'),
        ('books', '0002_remove_book_author_book_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.ForeignKey(db_column='author_name', default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authors', to='authors.author', verbose_name='author_name'),
        ),
    ]
