# Generated by Django 4.1.7 on 2023-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(db_column='name', max_length=100, primary_key=True, serialize=False)),
                ('year_born', models.CharField(max_length=10)),
                ('year_died', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(max_length=60)),
                ('books_written', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'dim_all_authors',
            },
        ),
    ]
