# Generated by Django 4.1.7 on 2023-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(db_column='author_name', default='Unknown', max_length=100, primary_key=True, serialize=False),
        ),
    ]
